export default {
  addCartButton: ".purchase-button",
  applyButton: ".discount>div",
  cartNavigation: "[href='/cart'] > .menu-item-small",
  chairDepartment: ".footer [href='/department/chairs']",
  discountCode: "input[placeholder='Discount code']",
  discountToast: ".discount-toast",
  navigationMenu: ".hamburger",
  productPrice: ".item .description .price",
  productPriceInCart: ".product-description > div > span",
  productStatus: "a > .product-card",
  productTitle: ".item .description > div > div",
  productTitleInCart: ".product-description > div:not(.product-bottom)",
  sofaDepartment: ".footer [href='/department/sofas']",
  totalPrice: "div[class='line line-total'] > div",
};